### ISSUE TITLE
Problem with conflict checking blocks scheduling teachers

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#1196]
Bling your bra - should be Jeannie and Devastasia, and the conflict checking broke when looking for a duration.

------------------

Internal Server Error: /scheduling/edit/Class/933/4032
Traceback (most recent call last):
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/gbelive/webapps/gbelivenew/expo/gbe/scheduling/views/make_occurrence_view.py", line 396, in dispatch
    return super(MakeOccurrenceView, self).dispatch(*args, **kwargs)
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gbelive/webapps/gbelivenew/lib/python2.7/Django-1.8.17-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gbelive/webapps/gbelivenew/expo/gbe/scheduling/views/make_occurrence_view.py", line 377, in post
    locations=[self.room])
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/idd/update_occurrence.py", line 41, in update_occurrence
    person).warnings
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/models.py", line 681, in allocate_person
    for conflict in worker.workeritem.get_conflicts(self):
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/models.py", line 473, in get_conflicts
    if event.check_conflict(new_event):
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/models.py", line 1022, in check_conflict
    self.end_time > other_event.start_time):
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/models.py", line 49, in end_time
    return self.starttime + self.duration
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/models.py", line 960, in duration
    return self.eventitem.duration
  File "/home/gbelive/webapps/gbelivenew/expo/scheduler/models.py", line 559, in duration
    return child.sched_duration
AttributeError: 'EventItem' object has no attribute 'sched_duration'

Request repr():
<WSGIRequest
path:/scheduling/edit/Class/933/4032,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'event-time': [u'13:00:00'], u'event-location': [u'301'], u'event-duration': [u'01:30:00'], u'submit': [u'Submit'], u'event-day': [u'22'], u'event-moderator': [u''], u'event-teacher': [u'946'], u'event-staff_lead': [u''], u'csrfmiddlewaretoken': [u'28s32PgyvLl6XN3N8dWibYDlfVSNHeNW'], u'event-e_title': [u'Bling Your Bra'], u'event-max_volunteer': [u'0'], u'event-e_description': [u"<p>Do you have a blah bra? Let Jeannie Martini and Devastasia show you how to dress to your champagne taste -- even when you've got a beer budget. Students will learn different techniques for designing and embellishing a bra. Please bring a bra you wish to decorate; started or not!</p>"]}>,
COOKIES:{'csrftoken': '28s32PgyvLl6XN3N8dWibYDlfVSNHeNW',
 'django_language': 'en-us',
 'sessionid': 'n3mmtwj1w5v14znrgi5wkfga0fs3j3w3'},
META:{'CONTENT_LENGTH': '1618',
 'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryEnBfPl9LLd3WNCtx',
 'CONTEXT_DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
 'CONTEXT_PREFIX': '',
 u'CSRF_COOKIE': u'28s32PgyvLl6XN3N8dWibYDlfVSNHeNW',
 'DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'django_language=en-us; sessionid=n3mmtwj1w5v14znrgi5wkfga0fs3j3w3; csrftoken=28s32PgyvLl6XN3N8dWibYDlfVSNHeNW',
 'HTTP_FORWARDED_REQUEST_URI': '/scheduling/edit/Class/933/4032',
 'HTTP_HOST': 'www.burlesque-expo.com',
 'HTTP_HTTPS': 'off',
 'HTTP_ORIGIN': 'http://www.burlesque-expo.com',
 'HTTP_REFERER': 'http://www.burlesque-expo.com/scheduling/edit/Class/933/4032',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '167.176.16.240',
 'HTTP_X_FORWARDED_HOST': 'www.burlesque-expo.com',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_FORWARDED_SERVER': 'www.burlesque-expo.com',
 'HTTP_X_FORWARDED_SSL': 'off',
 'LD_LIBRARY_PATH': '/home/gbelive/webapps/gbelivenew/apache2/lib:/home/gbelive/webapps/gbelivenew/lib',
 'PATH_INFO': u'/scheduling/edit/Class/933/4032',
 'PATH_TRANSLATED': '/home/gbelive/webapps/gbelivenew/expo/expo/wsgi.py/scheduling/edit/Class/933/4032',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '41504',
 'REQUEST_METHOD': 'POST',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/scheduling/edit/Class/933/4032',
 'SCRIPT_FILENAME': '/home/gbelive/webapps/gbelivenew/expo/expo/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'www.burlesque-expo.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.4.23 (Unix) mod_wsgi/4.5.9 Python/2.7',
 'apache.version': (2, 4, 23),
 'mod_wsgi.application_group': 'web559.webfaction.com|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.daemon_connects': '1',
 'mod_wsgi.daemon_restarts': '0',
 'mod_wsgi.daemon_start': '1513107573949894',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.ignore_activity': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '14264',
 'mod_wsgi.path_info': '/scheduling/edit/Class/933/4032',
 'mod_wsgi.process_group': 'gbelivenew',
 'mod_wsgi.queue_start': '1513107573949783',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.request_id': 'x8Rzz4HAAwA',
 'mod_wsgi.request_start': '1513107573949639',
 'mod_wsgi.script_name': '',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.script_start': '1513107573949929',
 'mod_wsgi.thread_id': 1,
 'mod_wsgi.thread_requests': 144L,
 'mod_wsgi.total_requests': 144L,
 'mod_wsgi.version': (4, 5, 8),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f5f44d90080>,
 'wsgi.file_wrapper': <type 'mod_wsgi.FileWrapper'>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f5f4462cf80>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by bethlakshmi** [comment]
There was a corrupted EventItem - I deleted it and everything now works.  Many, many things were broken for Jeannie, specifically, and I don't know why.
