### ISSUE TITLE
can't install deploy stack

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#399]
I am trying to install a deploy stack, as @burlexpo requested... and it's going unbelievably badly.

I did my normal process of pulling from GBE2 into the betty stack... and restarted and as soon as I hit the betty stack, I get a 200 error.  

The error is:

[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1] mod_wsgi (pid=921717): Exception occurred processing WSGI script '/home/gbeadmin/webapps/gbetest/deploy/stack/betty/expo/expo/wsgi.py'.
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1] Traceback (most recent call last):
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]   File "/home/gbeadmin/webapps/gbetest/deploy/stack/betty/expo/expo/wsgi.py", line 14, in <module>
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]     application = get_wsgi_application()
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]   File "/home/gbeadmin/bin/django/core/wsgi.py", line 14, in get_wsgi_application
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]     django.setup()
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]   File "/home/gbeadmin/bin/django/__init__.py", line 21, in setup
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]     apps.populate(settings.INSTALLED_APPS)
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]   File "/home/gbeadmin/bin/django/apps/registry.py", line 85, in populate
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]     app_config = AppConfig.create(entry)
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]   File "/home/gbeadmin/bin/django/apps/config.py", line 116, in create
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]     mod = import_module(mod_path)
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1]     __import__(name)
[Sun Mar 29 00:32:34 2015] [error] [client 127.0.0.1] ImportError: No module named sorl

I know that sorl is what we are using for thumbnails, but I'd have assumed if it was on the stack, it'd be accessible to all of us...  I tried installing mechanisms for sorl, but they aren't working and that seems like a crazy approach?

I'm now afraid of updating the code anywhere else, for fear of perpetuating the error... the betty stack was working fine today before I did this.

**Comment by bethlakshmi** [comment]
grrr...

I may be hungry and stupid...

from /home/gbeadmin/lib/python2.7
run:
pip install --user sorl-thumbnail

restart.
problem solved.
 sigh
