### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /costume/create

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#695]
Traceback (most recent call last):
      File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/gbelive/webapps/gbelive/lib/python2.7/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
      File "/home/gbelive/webapps/gbelive/expo/expo/gbe_logging.py", line 25, in __call__
    return funct(*args, **kwargs)
      File "/home/gbelive/webapps/gbelive/expo/gbe/views.py", line 2074, in bid_costume
    'performer': performers[0]})
      File "/home/gbelive/webapps/gbelive/lib/python2.7/django/db/models/query.py", line 132, in __getitem__
        return list(qs)[0]

IndexError: list index out of range

**Comment by jonkiparsky** [comment]
Resolved
