### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /scheduler/view_list/class/

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#715]
Traceback (most recent call last):

```
  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/gbelive/webapps/gbelive/expo/scheduler/views.py", line 986, in view_list
    {'title': list_titles[event_type],

KeyError: u'class'


<WSGIRequest
path:/scheduler/view_list/class/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'OYt5NuAciJjtazikmCgCkBJxfZlbTNkS',
 'DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_CONNECTION': 'close',
 'HTTP_FORWARDED_REQUEST_URI': '/scheduler/view_list/class/',
 'HTTP_HOST': 'burlesque-expo.com',
 'HTTP_HTTPS': 'off',
 'HTTP_HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_USER_AGENT': 'Domain Re-Animator Bot (http://domainreanimator.com) - support@domainreanimator.com',
 'HTTP_X_FORWARDED_FOR': '167.114.156.198',
 'HTTP_X_FORWARDED_HOST': 'burlesque-expo.com',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_FORWARDED_SERVER': 'burlesque-expo.com',
 'HTTP_X_FORWARDED_SSL': 'off',
 'PATH_INFO': u'/scheduler/view_list/class/',
 'PATH_TRANSLATED': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py/scheduler/view_list/class/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '36203',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/scheduler/view_list/class/',
 'SCRIPT_FILENAME': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'burlesque-expo.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.2.25 (Unix) mod_wsgi/3.5 Python/2.7.11',
 'mod_wsgi.application_group': 'web489.webfaction.com|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '14983',
 'mod_wsgi.process_group': 'gbelive',
 'mod_wsgi.queue_start': '1455427434455286',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 5),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f71b11bb3b0>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f71b150a828>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f71b11bbd30>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by jonkiparsky** [comment]
@bethlakshmi @BenignCremator Wow. We have case-sensitive URLs.
