### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /reports/schedule/all

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#721]
Traceback (most recent call last):

```

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/gbelive/webapps/gbelive/expo/gbe/report_views.py", line 206, in personal_schedule
    items = get_checklist_items(person, conference)

  File "/home/gbelive/webapps/gbelive/expo/gbe/ticketing_idd_interface.py", line 231, in get_checklist_items
    profile)

  File "/home/gbelive/webapps/gbelive/expo/gbe/ticketing_idd_interface.py", line 187, in get_checklist_items_for_tickets
    if not condition.is_excluded(tickets, profile, conference):

  File "/home/gbelive/webapps/gbelive/expo/ticketing/models.py", line 197, in is_excluded
    for exclusion in self.ticketing_ticketingexclusion.all():

AttributeError: 'TicketingEligibilityCondition' object has no attribute 'ticketing_ticketexclusion'


<WSGIRequest
path:/reports/schedule/all,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'y88pwYW7k04jwNYtOhXFmYx6X1QtoJ6a',
 'django_language': 'en-us',
 'sessionid': 'ikpww5pb80qp8274aja0c1nwbm13x7jj'},
META:{u'CSRF_COOKIE': u'y88pwYW7k04jwNYtOhXFmYx6X1QtoJ6a',
 'DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'django_language=en-us; csrftoken=y88pwYW7k04jwNYtOhXFmYx6X1QtoJ6a; sessionid=ikpww5pb80qp8274aja0c1nwbm13x7jj',
 'HTTP_FORWARDED_REQUEST_URI': '/reports/schedule/all',
 'HTTP_HOST': 'gbelive.webfactional.com',
 'HTTP_HTTPS': 'off',
 'HTTP_HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_REFERER': 'http://gbelive.webfactional.com/reports',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:43.0) Gecko/20100101 Firefox/43.0',
 'HTTP_X_FORWARDED_FOR': '71.234.102.29',
 'HTTP_X_FORWARDED_HOST': 'gbelive.webfactional.com',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_FORWARDED_SERVER': 'gbelive.webfactional.com',
 'HTTP_X_FORWARDED_SSL': 'off',
 'PATH_INFO': u'/reports/schedule/all',
 'PATH_TRANSLATED': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py/reports/schedule/all',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '39719',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/reports/schedule/all',
 'SCRIPT_FILENAME': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'gbelive.webfactional.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.2.25 (Unix) mod_wsgi/3.5 Python/2.7.11',
 'mod_wsgi.application_group': 'web489.webfaction.com|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '14983',
 'mod_wsgi.process_group': 'gbelive',
 'mod_wsgi.queue_start': '1454610323532295',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 5),
 'wsgi.errors': <mod_wsgi.Log object at 0x7ff8746bf1b0>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7ff86fb707b0>,
 'wsgi.input': <mod_wsgi.Input object at 0x7ff874434070>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by bethlakshmi** [comment]
refactoring has likely obliterated this
