### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /scheduler/contact_by_role/Volunteers

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#723]
Traceback (most recent call last):

```

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/gbelive/webapps/gbelive/expo/scheduler/views.py", line 737, in contact_by_role
    header, contact_info = contact_volunteers(conference)

  File "/home/gbelive/webapps/gbelive/expo/scheduler/views.py", line 672, in contact_volunteers
    allocation.event.as_subtype.volunteer_category, ''),

AttributeError: 'Show' object has no attribute 'volunteer_category'


<WSGIRequest
path:/scheduler/contact_by_role/Volunteers,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'FpdvMsFoLvCxCnS7wCj3iNTiL6Y9ttYs',
 'django_language': 'en-us',
 'sessionid': '8hnfqhkewywnndpgq47ab3pbwe1pbw78'},
META:{u'CSRF_COOKIE': u'FpdvMsFoLvCxCnS7wCj3iNTiL6Y9ttYs',
 'DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'django_language=en-us; sessionid=8hnfqhkewywnndpgq47ab3pbwe1pbw78; csrftoken=FpdvMsFoLvCxCnS7wCj3iNTiL6Y9ttYs',
 'HTTP_FORWARDED_REQUEST_URI': '/scheduler/contact_by_role/Volunteers',
 'HTTP_HOST': 'www.burlesque-expo.com',
 'HTTP_HTTPS': 'off',
 'HTTP_HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '73.16.153.57',
 'HTTP_X_FORWARDED_HOST': 'www.burlesque-expo.com',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_FORWARDED_SERVER': 'www.burlesque-expo.com',
 'HTTP_X_FORWARDED_SSL': 'off',
 'PATH_INFO': u'/scheduler/contact_by_role/Volunteers',
 'PATH_TRANSLATED': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py/scheduler/contact_by_role/Volunteers',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '33979',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/scheduler/contact_by_role/Volunteers',
 'SCRIPT_FILENAME': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'www.burlesque-expo.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.2.25 (Unix) mod_wsgi/3.5 Python/2.7.11',
 'mod_wsgi.application_group': 'web489.webfaction.com|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '14983',
 'mod_wsgi.process_group': 'gbelive',
 'mod_wsgi.queue_start': '1454520959851739',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 5),
 'wsgi.errors': <mod_wsgi.Log object at 0x7fd73d42c830>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7fd73d2f5be8>,
 'wsgi.input': <mod_wsgi.Input object at 0x7fd73ce80bb0>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by bethlakshmi** [comment]
Refactor for cleaning up the volunteer contact info has eliminated this bug.
Cannot reproduce.
Cannot find the line of problem code.
