### ISSUE TITLE
Revenge of webdev - Internal Server Error: /scheduler/Show/Saturday

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#786]
The latest fixes for WebDev emails are up on production, and we're still getting emails.

This one is for /scheduler/Show/Saturday or Sunday.

-Beth

---

[Django] ERROR (EXTERNAL IP): Internal Server Error: /scheduler/Show/Saturday

webdev@burlesque-expo.com

---

to info
Traceback (most recent call last):

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)

  File "/home/gbelive/webapps/gbelive/expo/scheduler/views.py", line 1023, in calendar_view
    cal_times = cal_times_for_conf(conf, day)

  File "/home/gbelive/webapps/gbelive/expo/scheduler/functions.py", line 446, in cal_times_for_conf
    day = date_to_datetime(select_day(days, day_name).day)

AttributeError: 'NoneType' object has no attribute 'day'

<WSGIRequest
path:/scheduler/Show/Saturday,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{u'CSRF_COOKIE': u'bXyhdEbtTNJnIr0rcVTbbWrS0hrVRPw6',
 'DOCUMENT_ROOT': '/usr/local/apache2/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8',
 'HTTP_ACCEPT_CHARSET': 'utf-8',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_FORWARDED_REQUEST_URI': '/scheduler/Show/Saturday',
 'HTTP_HOST': 'gbelive.webfactional.com',
 'HTTP_HTTPS': 'off',
 'HTTP_HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_REFERER': 'http://gbelive.webfactional.com',
 'HTTP_STRICTSSL': 'false',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0',
 'HTTP_X_FORWARDED_FOR': '45.55.229.99',
 'HTTP_X_FORWARDED_HOST': 'gbelive.webfactional.com',
 'HTTP_X_FORWARDED_PROTO': 'http',
 'HTTP_X_FORWARDED_SERVER': 'gbelive.webfactional.com',
 'HTTP_X_FORWARDED_SSL': 'off',
 'PATH_INFO': u'/scheduler/Show/Saturday',
 'PATH_TRANSLATED': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py/scheduler/Show/Saturday',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '35162',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/scheduler/Show/Saturday',
 'SCRIPT_FILENAME': '/home/gbelive/webapps/gbelive/expo/expo/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'gbelive.webfactional.com',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.2.25 (Unix) mod_wsgi/3.5 Python/2.7.11',
 'mod_wsgi.application_group': 'web489.webfaction.com|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '14983',
 'mod_wsgi.process_group': 'gbelive',
 'mod_wsgi.queue_start': '1462716523128856',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 5),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f71b1691530>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f71b1507828>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f71b15bb370>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by bethlakshmi** [comment]
#1115 deprecates this problem
