### ISSUE TITLE
Costume review detail links are failing.

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#794]
Links from the costume review list (http://www.burlesque-expo.com/costume/reviewlist?conf_slug=GBE2016) are failing. 
Example: Hedy Jo Starr "Green" (http://www.burlesque-expo.com/costume/review/527)
gets a 500 error

```
Traceback (most recent call last):

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/gbelive/webapps/gbelive/lib/python2.7/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/gbelive/webapps/gbelive/expo/expo/gbe_logging.py", line 25, in __call__
    return funct(*args, **kwargs)

  File "/home/gbelive/webapps/gbelive/expo/gbe/views/review_costume_view.py", line 43, in ReviewCostumeView
    return view_costume(request, costume_id)

NameError: global name 'view_costume' is not defined
```

**Comment by bethlakshmi** [comment]
An interesting detail... this is happening when the conference is past, and not when the conference is current:

http://gbe2016test.gbeadmin.webfactional.com/costume/review/527

is not 100% the same data, but the costume details should be the same (the DB capture was taken a week or so before the GBE 2016 expo).

And both test and live are on the same code base right now (unless someone else updated it this month).

And we didn't have costumes in 2015...

I'm up for taking this one.
